// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnEaMkg6TXFdfb8r5AU1RI_1tocKI2TdM',
    appId: '1:6472754643:web:02c6079f8e6b2a4128bb26',
    messagingSenderId: '6472754643',
    projectId: 'blogs-7fc7b',
    authDomain: 'blogs-7fc7b.firebaseapp.com',
    storageBucket: 'blogs-7fc7b.appspot.com',
    measurementId: 'G-WKLSQ4G75G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxiveZ68ZgquFnplithwhda8NGt3_JB0',
    appId: '1:6472754643:android:440cf829241248f528bb26',
    messagingSenderId: '6472754643',
    projectId: 'blogs-7fc7b',
    storageBucket: 'blogs-7fc7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXlWZr_lQ12GvEY40EX6I3qG8PEFvXJOA',
    appId: '1:6472754643:ios:03407126fd91a3b728bb26',
    messagingSenderId: '6472754643',
    projectId: 'blogs-7fc7b',
    storageBucket: 'blogs-7fc7b.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );
}
